### ISSUE TITLE
Open files from remote pc

### ISSUE THREAD

**Issue by funivan** [zolotov/RemoteCall#10]
Hi. Is there any way to open files in my phpstorm from remote pc. 
For example my local ip is 192.168.1.11 my friend ip is 192.168.1.12  
I think my friend can request http://192.168.1.11:8091/?message=App.php:14 and file will be opened in my phpstorm

I try this but it doesn’t work. Probably reason is in  ``new InetSocketAddress("localhost", port);`

@zolotov  there are 2 questions for you:
1. It is possible to do that?
2. Can you make this as an option?

**Comment by prestonweslly4-prog** [comment]
What do you mean by merged need an idea I'm working on
