### ISSUE TITLE
Add an option to make phpStorm to foreground

### ISSUE THREAD

**Issue by Geolim4** [zolotov/RemoteCall#12]
Hi !!
It is possible to add an option to make phpStorm to foreground once he received the localhost call ?
Cheers,

**Comment by zolotov** [comment]
The plugin tries to do it but it's not always possible. Anyway I'm not going improve the plugin anymore. For now the recommended way to open files by http requests in using built-in PhpStorm Rest API: http://develar.org/idea-rest-api/#api-Platform-file

**Comment by Geolim4** [comment]
Ok great, thanks !!
