### ISSUE TITLE
Launching a file in the root of a project

### ISSUE THREAD

**Issue by jalara** [zolotov/RemoteCall#13]
Hello,

Fantastic plugin, has help me work a lot faster.

But I am having a problem:
When I try to launch a file with an ambiguous name (like index.html) that resides in the root directory of my project, the plugin is unable to target the 'index.html' in my root when there is an 'index.html' in a sub-folder. The plugin always goes to first using the following request:
http://localhost:8091/?message=index.html:1

I tried to change the file path to this but didn't have any luck:
http://localhost:8091/?message=/index.html:1

Please advise,
Thank you in advance,
Jamie

**Comment by zolotov** [comment]
Hi @jalara,

I'm not going improve the plugin anymore, but you can fix the issue by yourself. There is a code that tries to define which file should be opened: https://github.com/zolotov/RemoteCall/blob/master/src/main/java/com/farpost/intellij/remotecall/utils/FileNavigatorImpl.java#L27 

For now the recommended way to open files by http requests in using built-in PhpStorm Rest API: http://develar.org/idea-rest-api/#api-Platform-file

**Comment by suside** [comment]
I know this is not the best place to ask this but develar.org site is down (404).
Is that API official? I can't find any documentation on google :(

**Comment by zolotov** [comment]
@suside yes, the API is official. develar.org is up now, thank you.
